### ISSUE TITLE
Clarification of categorical variables

### ISSUE THREAD

**Issue by dionnecargy** [Greenhouse-Lab/THEREALMcCOIL#10]
Hi there, I would just like some clarification on the categorical variables in the test file. I can understand that -1 and 1 are the homozygotes and 0 is a heterozygote? Then what would 0.5 and/or -0.5 mean? Thanks!

**Comment by m-murphy** [comment]
Hi, for the categorical method, 0 is homozygous minor, 0.5 is heterozygous, 1 is homozygous major and -1 indicates missing data.

**Comment by dionnecargy** [comment]
Thank you for clarifying!! :)
