### ISSUE TITLE
README does not explain error_method 3

### ISSUE THREAD

**Issue by gustavo11** [Greenhouse-Lab/THEREALMcCOIL#2]

**Comment by hhchang** [comment]
If error_method=3, e1 and e2 are estimated with COI and allele frequencies. Please check README.docx instead of README.md. We will modify .md file soon! 

-Hsiao-Han

**Comment by m-murphy** [comment]
This has been resolved with commit ca816d71ef1003225adb2429dc9857ab775203ca
