### ISSUE TITLE
Web version of COIL on broadinstitute.org 504 Gateway Timeout

### ISSUE THREAD

**Issue by xgao32** [Greenhouse-Lab/THEREALMcCOIL#5]
@hhchang 

I tried submitting a 500kb text file with the option of estimating MAF directly from SNP barcode data and kept getting the following

![image](https://user-images.githubusercontent.com/6380557/40156776-90c8103a-5969-11e8-8505-e2b51bbcbfb8.png)

Please advise on how best to proceed with this [text file](https://drive.google.com/open?id=1timTFNOG-vvJih0DauErUlO4jyob2yPU) . Thanks

**Comment by xgao32** [comment]
A truncated version of the text file of 1kb seems to work fine.

```PG0390 TCNGGAGAGNNNGTNTNNTNNNACC
PG0391 TCNGGAGAGNNNGTNTNNTNNNACC
PG0392 TCNGGAGAGNNNGTNTNNTNNNACC
PG0393 TCNGGAGAGNNNGTNTNNTNNNACC
PG0394 TCTGGAGAGNGNGTNTNNTGAAACC
PG0395 NNNNNNNNNNNTNTNNNNNGNNNCC
PG0396 NNNNNNNNNNNTNTNNNNNGNNNNN
PG0397 NNNNNNNNNNNTNTNNNNNGNNNXC
PG0398 TCTAAGTCTAATATTCTTTGTGACC
PG0399 TCTAAGTCTAATATTCTTTGTGACC
PG0400 TCTAAGTCTAATATTCTTTGTGACC
PG0401 TNTNNNNNTANTATTCTTTGTGACC
PG0402 NNTNNNNNNANTNTTCTTNGTGACC
PG0403 NNNNNNNNNANTNTTCTTNGTGNNN
PG0404 NNNNNNNNNANTNTTCTTNGTGNCC
PG0405 NNNNNNNNNANTNTTCTTNGTGNCC
PG0406 NNNNNNNNNANTNTTCTTNGTGNNN
PG0407 NNNNNNNNNANTNTTCTTNGTGNNC
PG0408 NNNNNNNNNANTNTTCTTNGTGNNN
PG0409 NNNNNNNNNANTNTTCTTNGTGNCC
PG0410 NNNNNNNNNANTNTTCTTNGTGNNN
PG0411 NNNNNNNNNANTNTTCTTNGTGNXX
PG0412 NNNNNNNNNANTNTTCTTNGTGNXX
PG0413 ANGGGAGAGAGTGTTCTTCGTGGXX
PG0414 ANGGGAGAGAGTGTTCTTCGTGGTT
PG0415 ANGGGAGAGAGTGTTCTTCGTGGTT
PG0389 TCNGGAGAGANGGTNTNNTTTNACC
PG0390 TCNGGAGAGNNNGTNTNNTNNNACC
```

**Comment by tmfarrell** [comment]
Hey @gaomrx, 

Sorry for the delay in getting back.  As you've found, the issue had to do with the size of your input.  COIL has mainly been used on barcodes of length 100 or less, so we really haven't tested its performance on anything much larger than that.

That said, all I had to do was increase the socket/ response timeout limits and the maximum allowable COI from their defaults.  Now it works on your sized input (>17000 positions for >25 samples) and seems to give back reasonable results, though it does take 5 minutes or so. 

Let us know if you run into any other issues. 

Best, Tim

**Comment by tmfarrell** [comment]
I should mention, however, that THE REAL MCCOIL shouldn't be enabled when running on this large of input. This bumps up against the memory limitations of the VM and probably won't be supported anytime soon.

**Comment by hhchang** [comment]
Thank you @gaomrx for your interest and thank you @tmfarrell for help! In order to use THE REAL McCOIL, I recommend excluding SNPs with small minor allele frequencies to reduce the total number of SNPs.

**Comment by xgao32** [comment]
@hhchang @tmfarrell Thanks for your helpful feedbacks. I think it maybe best for me to use the R wrapper around THE REAL MCCOIL for fuller control over different parameters. May I ask if COIL is actually preferred over THE REAL MCCOIL or vice versus? THE REAL MCCOIL paper shows "better" results than COIL and the author of COIL has dropped support for it.
