### ISSUE TITLE
R test files not working

### ISSUE THREAD

**Issue by dionnecargy** [Greenhouse-Lab/THEREALMcCOIL#9]
Hi there, I am trying to get the R version of THE REAL McCOIL categorical method to work on my Mac (Big Sur 11.5.2) however it keeps coming up with this error. 

Error in dyn.load(paste(path, mcCoil_categorical_code_location, sep = "")) : 
  unable to load shared object '[PATH]categorical_method/McCOIL_categorical_code.so':
  dlopen([PATH]categorical_method/McCOIL_categorical_code.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.2/Resources/lib/libR.dylib
  Referenced from:[PATH]categorical_method/McCOIL_categorical_code.so
  Reason: image not found

I have the correct PATH and it still won't work. It appears that R won't read the .so object. Could someone please help me with this?

**Comment by m-murphy** [comment]
Hi, that error message suggests that the path is not being parsed correctly. I assume you've replaced your actual path with [PATH] in your message because it's sensitive. Could you please confirm that the path is correct by copy and pasting directly from the error message into your terminal `ls [PATH]/categorical_method` and confirm the .so file is there?

**Comment by dionnecargy** [comment]
Hi! Thanks for responding - yes the file is there when I type that code into the terminal, and I can physically see the file too, yet I still get that error code. I have been trying to find solutions on the internet as well to see if this is a problem with R Studio or Mac's, but I have not found any solution.

**Comment by m-murphy** [comment]
Ok, one other thing you could try is to rebuild the functions. To do this, `cd` into the categorical method directory, then run `R CMD SHLIB McCOIL_categorical_code.c llfunction_het.c`

this will rebuild the `.so` file and will hopefully help

**Comment by dionnecargy** [comment]
Hi there, thanks for that code! However, the error still comes up :(

**Comment by m-murphy** [comment]
I forgot to mention, you should remove the `.so` files that are already there before running that command by running `rm *.o *.so` within the categorical method directory. If you did do that, then this is very odd, I'm not sure what is going on.

**Comment by dionnecargy** [comment]
Omg it worked!! Thank you so much! :)

**Comment by m-murphy** [comment]
Great! glad I could help

**Comment by dionnecargy** [comment]
Hi there - I was wondering if you knew how to convert the terminal code above to work for Windows - I have a colleague that is finding it difficult to transfer the code above. Thanks.

**Comment by m-murphy** [comment]
`R CMD SHLIB McCOIL_categorical_code.c llfunction_het.c` should still work I think, but the output will be a `.dll` file rather than a `.so` file. The code would then need to be modified to refer to this `.dll` file rather than the `.so` file.
